#!/bin/bash
#_(
   #_DEPS is same format as deps.edn. Multiline is okay.
   DEPS='{:deps {
                 clj-time {:mvn/version "0.14.2"}
                }}'
   
   #_You can put other options here
   OPTS='-J-Xms256m -J-Xmx256m -J-client'
   
   exec clojure $OPTS -Sdeps "$DEPS" "$0" "$@"
)
;; Written by Eric Normand and published here: 
;; https://gist.github.com/ericnormand/6bb4562c4bc578ef223182e3bb1e72c5
;; Clojure code goes here ....

(require '[clojure.java.io :as io]
         '[clojure.java.shell :as sh]
         '[clojure.edn :as edn]
         '[clojure.string :as str]
         '[clojure.pprint :as pp])

(println "The full path name of the file containing this code becomes the\n"
         "value of the Clojure variable *file*:\n"
         *file*)
(println)
(println "The base name of the file containing this code becomes the\n"
         "value of the Clojure variable *source-path*:\n"
         *source-path*)
(println)
(println "Any command line arguments given after the name of this file\n"
         "become the value of the Clojure variable *command-line-args*,\n"
         "which is a list of strings.  It never contains the name of the\n"
         "command, and is an empty list if no arguments are given for the\n"
         "command:")
(pr *command-line-args*)
(println)
(println)

(println "Clojure version:" (clojure-version))
(println "Hello, world!")

;; If you ever call future or clojure.java.shell/sh, this will avoid a
;; 60-second wait when the sript is done, until it exits.
(shutdown-agents)
